In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import load_model
import tensorflow as tf
from sklearn.metrics import confusion_matrix, accuracy_score
from pickle import dump,load

In [3]:
!rm -r ML-FINAL-EXAM//  
!git clone https://github.com/VingardiumGloriosa/ML-FINAL-EXAM

rm: cannot remove 'ML-FINAL-EXAM/': No such file or directory
Cloning into 'ML-FINAL-EXAM'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 15 (delta 3), reused 13 (delta 1), pack-reused 0
Unpacking objects: 100% (15/15), done.


In [4]:
dataFrame = pd.read_csv('ML-FINAL-EXAM/b_depressed.csv') 

In [5]:
dataFrame.head()

Survey_id  Ville_id  sex  Age  Married  Number_children  education_level  \
0        926        91    1   28        1                4               10   
1        747        57    1   23        1                3                8   
2       1190       115    1   22        1                3                9   
3       1065        97    1   27        1                2               10   
4        806        42    0   59        0                4               10   

   total_members  gained_asset  durable_asset  ...  incoming_salary  \
0              5      28912201       22861940  ...                0   
1              5      28912201       22861940  ...                0   
2              5      28912201       22861940  ...                0   
3              4      52667108       19698904  ...                0   
4              6      82606287       17352654  ...                1   

   incoming_own_farm  incoming_business  incoming_no_business  \
0                  0                  0                     0   
1                  0                  0                     0   
2                  0                  0                     0   
3                  1                  0                     1   
4                  0                  0                     0   

   incoming_agricultural  farm_expenses  labor_primary  lasting_investment  \
0               30028818       31363432              0            28411718   
1               30028818       31363432              0            28411718   
2               30028818       31363432              0            28411718   
3               22288055       18751329              0             7781123   
4               53384566       20731006              1            20100562   

   no_lasting_investmen  depressed  
0            28292707.0          0  
1            28292707.0          1  
2            28292707.0          0  
3            69219765.0          0  
4            43419447.0          0  

[5 rows x 23 columns]

In [6]:
dataFrame.isnull().sum()
dataFrame.dropna(inplace=True)

In [7]:
pd.set_option('display.max_columns', None) 
X = dataFrame.iloc[:,:5] 
X.drop(columns=['Survey_id','Ville_id'], axis=1, inplace=True)
y = dataFrame.iloc[:,-1] 
print(X.iloc[0:5,:])

   sex  Age  Married
0    1   28        1
1    1   23        1
2    1   22        1
3    1   27        1
4    0   59        0


In [8]:
X = pd.get_dummies(X) 
columnNames = list(X.columns) 
X = X.values 
y = y.values

In [9]:
print(X.shape)
print(X)
print(y)

(1409, 3)
[[ 1 28  1]
 [ 1 23  1]
 [ 1 22  1]
 ...
 [ 1 66  0]
 [ 1 51  1]
 [ 1 33  0]]
[0 1 0 ... 1 0 0]


In [10]:
scaler = StandardScaler()
X = scaler.fit_transform(X) 

In [12]:
print(X)
print(y)
print(X.shape)

[[ 0.2981136  -0.48810848  0.5398849 ]
 [ 0.2981136  -0.85053726  0.5398849 ]
 [ 0.2981136  -0.92302302  0.5398849 ]
 ...
 [ 0.2981136   2.26635024 -1.85224664]
 [ 0.2981136   1.1790639   0.5398849 ]
 [ 0.2981136  -0.1256797  -1.85224664]]
[0 1 0 ... 1 0 0]
(1409, 3)


In [13]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 42 )

In [14]:
model = Sequential()
model.add(Dense(4,activation='relu'))
model.add(Dense(5,activation='relu'))
model.add(Dense(6,activation='relu'))
model.add(Dense(1,activation='sigmoid')) 

adam = Adam(learning_rate=0.001) 
model.compile(loss='binary_crossentropy', optimizer=adam, metrics = ['accuracy'])

In [27]:
model.fit(X_train,y_train,epochs=100, verbose=1)

Epoch 1/100
36/36 [==============================] - 0s 2ms/step - loss: 0.4490 - accuracy: 0.8279
Epoch 2/100
36/36 [==============================] - 0s 2ms/step - loss: 0.4489 - accuracy: 0.8279
Epoch 3/100
36/36 [==============================] - 0s 2ms/step - loss: 0.4489 - accuracy: 0.8279
Epoch 4/100
36/36 [==============================] - 0s 2ms/step - loss: 0.4487 - accuracy: 0.8279
Epoch 5/100
36/36 [==============================] - 0s 2ms/step - loss: 0.4488 - accuracy: 0.8279
Epoch 6/100
36/36 [==============================] - 0s 2ms/step - loss: 0.4490 - accuracy: 0.8279
Epoch 7/100
36/36 [==============================] - 0s 2ms/step - loss: 0.4488 - accuracy: 0.8279
Epoch 8/100
36/36 [==============================] - 0s 2ms/step - loss: 0.4490 - accuracy: 0.8279
Epoch 9/100
36/36 [==============================] - 0s 2ms/step - loss: 0.4495 - accuracy: 0.8279
Epoch 10/100
36/36 [==============================] - 0s 2ms/step - loss: 0.4489 - accuracy: 0.8279
Epoch 11/

In [ ]:
loss = model.history.history['loss']
sns.lineplot(x=range(len(loss)),y=loss)

In [28]:
model.evaluate(X_test,y_test) 

9/9 [==============================] - 0s 2ms/step - loss: 0.4247 - accuracy: 0.8546


[0.424739271402359, 0.8546099066734314]

In [37]:
print(columnNames)
prediction = model.predict([[0,25,1]])
print(prediction)

['sex', 'Age', 'Married']
[[0.20508593]]
